version: '3.8'

services:
  # Development service
  backend-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    container_name: shortlink-backend-dev
    ports:
      - '3001:${PORT:-3001}'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=${PORT:-3001}
    env_file:
      - .env
    command: npm run start:dev
    restart: unless-stopped
    networks:
      - shortlink-network

  # Production service
  backend-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: shortlink-backend-prod
    ports:
      - '3001:${PORT:-3001}'
    environment:
      - NODE_ENV=production
      - PORT=${PORT:-3001}
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - shortlink-network

networks:
  shortlink-network:
    driver: bridge
